name: GitHub Actions Demo

on:
  push:
    branches:
      - main  # or 'master' if that is your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f3004510@ds.study.iitm.ac.in
        run: echo "Hello, world!"
